// <auto-generated />
using System;
using API_HotelBooking.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_HotelBooking.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250424023010_addlp")]
    partial class addlp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_HotelBooking.Models.DanhGia", b =>
                {
                    b.Property<int>("MaDG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDG"));

                    b.Property<string>("BinhLuan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaND")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.HasKey("MaDG");

                    b.HasIndex("MaND");

                    b.ToTable("DanhGias");
                });

            modelBuilder.Entity("API_HotelBooking.Models.DatDichVu", b =>
                {
                    b.Property<int>("MaDDV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDDV"));

                    b.Property<int>("MaDP")
                        .HasColumnType("int");

                    b.Property<int>("MaDV")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaDDV");

                    b.HasIndex("MaDP");

                    b.HasIndex("MaDV");

                    b.ToTable("DatDichVus");
                });

            modelBuilder.Entity("API_HotelBooking.Models.DatPhong", b =>
                {
                    b.Property<int>("MaDP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDP"));

                    b.Property<int?>("MaKM")
                        .HasColumnType("int");

                    b.Property<int>("MaND")
                        .HasColumnType("int");

                    b.Property<int>("MaP")
                        .HasColumnType("int");

                    b.Property<int>("SoNguoi")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianCheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianCheckOut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianDat")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDP");

                    b.HasIndex("MaKM");

                    b.HasIndex("MaND");

                    b.HasIndex("MaP");

                    b.ToTable("DatPhongs");
                });

            modelBuilder.Entity("API_HotelBooking.Models.DichVu", b =>
                {
                    b.Property<int>("MaDV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDV"));

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("KieuDichVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDV");

                    b.ToTable("DichVus");
                });

            modelBuilder.Entity("API_HotelBooking.Models.KhuyenMai", b =>
                {
                    b.Property<int>("MaKM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKM"));

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<float>("PhanTramKM")
                        .HasColumnType("real");

                    b.Property<string>("TenKM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKM");

                    b.ToTable("KhuyenMais");
                });

            modelBuilder.Entity("API_HotelBooking.Models.LoaiPhong", b =>
                {
                    b.Property<int>("MaLP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLP"));

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLP");

                    b.ToTable("LoaiPhongs");
                });

            modelBuilder.Entity("API_HotelBooking.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaND")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaND"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaND");

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("API_HotelBooking.Models.Phong", b =>
                {
                    b.Property<int>("MaP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaP"));

                    b.Property<decimal>("GiaPhong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaLP")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongNguoiToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaP");

                    b.HasIndex("MaLP");

                    b.ToTable("Phongs");
                });

            modelBuilder.Entity("API_HotelBooking.Models.ThanhToan", b =>
                {
                    b.Property<int>("MaTT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTT"));

                    b.Property<int>("MaDP")
                        .HasColumnType("int");

                    b.Property<decimal>("TienThanhToan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TongNgayO")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTT");

                    b.HasIndex("MaDP")
                        .IsUnique();

                    b.ToTable("ThanhToans");
                });

            modelBuilder.Entity("API_HotelBooking.Models.DanhGia", b =>
                {
                    b.HasOne("API_HotelBooking.Models.NguoiDung", "NguoiDung")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaND")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("API_HotelBooking.Models.DatDichVu", b =>
                {
                    b.HasOne("API_HotelBooking.Models.DatPhong", "DatPhong")
                        .WithMany("DatDichVus")
                        .HasForeignKey("MaDP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_HotelBooking.Models.DichVu", "DichVu")
                        .WithMany("DatDichVus")
                        .HasForeignKey("MaDV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatPhong");

                    b.Navigation("DichVu");
                });

            modelBuilder.Entity("API_HotelBooking.Models.DatPhong", b =>
                {
                    b.HasOne("API_HotelBooking.Models.KhuyenMai", "KhuyenMai")
                        .WithMany("DatPhongs")
                        .HasForeignKey("MaKM");

                    b.HasOne("API_HotelBooking.Models.NguoiDung", "NguoiDung")
                        .WithMany("DatPhongs")
                        .HasForeignKey("MaND")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_HotelBooking.Models.Phong", "Phong")
                        .WithMany("DatPhongs")
                        .HasForeignKey("MaP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhuyenMai");

                    b.Navigation("NguoiDung");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("API_HotelBooking.Models.Phong", b =>
                {
                    b.HasOne("API_HotelBooking.Models.LoaiPhong", "LoaiPhong")
                        .WithMany("Phongs")
                        .HasForeignKey("MaLP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiPhong");
                });

            modelBuilder.Entity("API_HotelBooking.Models.ThanhToan", b =>
                {
                    b.HasOne("API_HotelBooking.Models.DatPhong", "DatPhong")
                        .WithOne("ThanhToan")
                        .HasForeignKey("API_HotelBooking.Models.ThanhToan", "MaDP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatPhong");
                });

            modelBuilder.Entity("API_HotelBooking.Models.DatPhong", b =>
                {
                    b.Navigation("DatDichVus");

                    b.Navigation("ThanhToan")
                        .IsRequired();
                });

            modelBuilder.Entity("API_HotelBooking.Models.DichVu", b =>
                {
                    b.Navigation("DatDichVus");
                });

            modelBuilder.Entity("API_HotelBooking.Models.KhuyenMai", b =>
                {
                    b.Navigation("DatPhongs");
                });

            modelBuilder.Entity("API_HotelBooking.Models.LoaiPhong", b =>
                {
                    b.Navigation("Phongs");
                });

            modelBuilder.Entity("API_HotelBooking.Models.NguoiDung", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("DatPhongs");
                });

            modelBuilder.Entity("API_HotelBooking.Models.Phong", b =>
                {
                    b.Navigation("DatPhongs");
                });
#pragma warning restore 612, 618
        }
    }
}
